- name: SGD
  lr: 5.0e-4
  match_rule: None
  except_rule: None
  no_weight_decay: false
  weight_decay: 1.0e-3
  momentum: 0.95
  nesterov: True
  lr_scheduler:
    mode: cos_lr
    base_lr: 5.0e-4
    target_lr: 5.0e-8

    decay_factor: 0.1 # for step mode
    milestones: [0.3, 0.6, 0.9]
    poly_power: 2.0 # for poly mode
    lr_decay: 0.9

    warm_up_from: 0.0
    warm_up_steps: 0
